### ISSUE TITLE
multiple CA or CA pathes in one playbook?

### ISSUE THREAD

**Issue by FleischKarussel** [andrewrothstein/ansible-trust-ca#3]
Hey Andrew,

I'm really glad you created and upload the ansible roles like trust-ca to the ansible galaxy.
I might not understand how to use multiple CAs at once to push and apply to a host.

In my case there is an enterprise root CA and a department CA that needs to be applied.
In the ansible folder structure I created ~/files/ca/enterpriseca/ca.pem and ~/files/ca/deptca/ca.pem.

have you got an idea how I can setup the playbook with that variable?

hosts: all
  roles:
    - role: andrewrothstein.trust-ca
      trust_ca_pki_dir: ~/files/ca/enterpriseca/ca.pem

and now going on?

Thanks!

Br
Benjamin

**Comment by FleischKarussel** [comment]
it was too simple... :/

```
- hosts: all
  roles:
    - role: andrewrothstein.trust-ca
      trust_ca_pki_dir: "{{ role_path }}/files/ca/deptca"
    - role: andrewrothstein.trust-ca
      trust_ca_pki_dir: "{{ role_path }}/files/ca/enterpriseca"
```
